### ISSUE TITLE
Support invokable controllers

### ISSUE THREAD

**Issue by nesl247** [kleijnweb/php-api-routing-bundle#2]
If the operationId matches an invokable controller (http://symfony.com/doc/current/controller/service.html#invokable-controllers), it should be used.

For example: `operationId: Some\\FQDN\\To\\An\\Action` should be completely valid and not require any of the `x-controller` stuff.

Having to put `:__invoke` is the only current way to workaround this due to the hard coded check for `:`.

I believe the way to do this is to check for `is_callable($operationId)`.

**Comment by johnknl** [comment]
This bundle is set up to use DI keys. You don't need `x-controller` or `x-controller-router`, but you do need to define your [controllers as services](https://symfony.com/doc/current/controller/service.html).

I highly recommend using the DI container as a proper DI container and not as a Registry (fetching services by keys in controller code), which means you would need to do this anyway.

If you prefer *not* to apply IoC and use the container as a Registry, you are free to add support for non-DI controller keys using a merge request.

**Comment by nesl247** [comment]
I haven't actually used the bundle yet, but was reading the docs and based on that and the code, it doesn't seem that it supports invokable controllers. I'm actually using the swagger-bundle, and saw that v4 uses this bundle for the route handling.

If we look at https://github.com/kleijnweb/php-api-routing-bundle/blob/master/src/Routing/OpenApiRouteLoader.php#L169 we see that unless the `operationId` contains `:`, which is the method separator, than it will require either `x-router-controller` or `x-router-controller-method`.

An invokable controller is:

```php
<?php

namespace Some\Namespace;

class SomeAction
{
    public function __invoke(...): Response
    {
        //...
        return new Response();
    }
}
```

With Symfony autowiring `Some\Namespace\SomeAction` as the serviceId. In this case, the controller method does not need to be specified because it is invokable, and thus ` Some\Namespace\SomeAction` is completely valid. In YAML, it would simply be written as `controller: Some\Namespace\SomeAction`.

**Comment by johnknl** [comment]
Fair enough. PRs are always welcome.
